model:
  target: src.stage1.models.dual_entropy_model.DualGrainVQModel
  params:
    encoderconfig:
      target: src.stage1.modules.dynamic_modules.encoder_dual.DualGrainEncoder
      params:
        ch: 128
        ch_mult: [1, 1, 2, 2, 4]
        num_res_blocks: 2
        attn_resolutions: [16, 32]
        dropout: 0.0
        resamp_with_conv: true
        in_channels: 3
        resolution: 256
        z_channels: 256
        router_config:
          target: src.stage1.modules.dynamic_modules.router_dual.DualGrainDynamicEntropyRouter
          params:
            fine_grain_ratio_min: 0.01
            fine_grain_ratio_max: 0.99
    decoderconfig:
      target: src.stage1.modules.dynamic_modules.decoder.Decoder
      params:
        ch: 128
        in_ch: 256
        out_ch: 3
        ch_mult: [1, 1, 2, 2]
        num_res_blocks: 2
        resolution: 256
        attn_resolutions: [32]
        latent_size: 32
        window_size: 2
        position_type: rope+learned
    lossconfig:
      target: src.stage1.modules.losses.vq_lpips_multidisc.VQLPIPSWithDiscriminator
      params:
        disc_start: 0
        disc_config:
          target: src.stage1.modules.discriminator.model.NLayerDiscriminator
          params:
            input_nc: 3
            ndf: 64
            n_layers: 3
            use_actnorm: false
        disc_init: true
        codebook_weight: 1.0
        pixelloss_weight: 1.0
        disc_factor: 1.0
        disc_weight: 1.0
        perceptual_weight: 1.0
        disc_conditional: false
        disc_loss: hinge
        disc_weight_max: 0.75
        budget_loss_config:
          target: src.stage1.modules.dynamic_modules.budget.BudgetConstraint_RatioMSE_DualGrain
          params:
            target_ratio: 0.5
            gamma: 10.0
            min_grain_size: 16
            max_grain_size: 32
            calculate_all: True
    vqconfig:
      target: src.stage1.modules.vector_quantization.masked_vq.MaskVectorQuantize
      params:
        codebook_size: 1024
        codebook_dim: 256
        channel_last: false
        accept_image_fmap: true
        commitment_beta: 0.25
        decay: 0.99
        restart_unused_codes: True
    quant_before_dim: 256
    quant_after_dim: 256
    quant_sample_temperature: 0.0
    image_key: input

scheduler:
  base_learning_rate: 4.5e-06
  warmup_epochs: 0
  warmup_epochs_ratio: 0.1
  scheduler_type: linear-warmup_cosine-decay

data:
  target: src.data.databuilder.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 4
    train_val: False
    train:
      target: src.data.imagenet.ImageNetDataset
      params:
        split: train
        config:
          data_dir: ../dataset/imagenet-mini/train
          size: 256
          random_crop: True
    val:
      target: src.data.imagenet.ImageNetDataset
      params:
        split: val
        config:
          data_dir: ../dataset/imagenet-mini/val
          size: 256
          random_crop: False
